# Generated by Django 4.2.4 on 2023-08-26 09:35

from django.db import migrations, models
import wwhg_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('wwhg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='+372000000', max_length=15, validators=[wwhg_app.models.validate_phone_number]),
        ),
    ]
