# Generated by Django 4.2.4 on 2023-08-11 21:15

from django.db import migrations, models
import wwhg_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('wwhg_app', '0003_category_order_product_delete_item_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=wwhg_app.models.filepath),
        ),
    ]
